//
//  PlotTests.swift
//  mdTests (macOS)
//
//  The ```plot fence, against the oracle the site itself produced.
//
//  WHERE THE EXPECTATIONS COME FROM
//  --------------------------------
//  `PlotVectors/plot-vectors.json` was generated by running nettrash.me's own
//  Rust — `render_plot_svg`, `nice_step`, `format_label` and
//  `preprocess_math_expr`, extracted verbatim from
//  `frontend/src/components/math.rs` — over 403 inputs: 81 tick spacings, 100
//  tick labels (each with the four Rust primitives that produced it), 162
//  evaluations, 38 malformed expressions and 22 whole figures. Every number in
//  it is recorded twice, once as JSON and once as the IEEE-754 bit pattern, so
//  "close enough" cannot creep in.
//
//  It is an oracle, not a specification. Six of the behaviours it records are
//  bugs, and this suite asserts the **fixed** behaviour for those, in a table
//  that names each one and what the site did. Everything else must match the
//  vector exactly — there is no third category, and no row is skipped: a row
//  either matches its vector or appears in one of the correction tables below.
//
//  This file is the twin of `md.vscode/test/plot.test.ts`, case for case, and
//  reads the same JSON. §9 pins the same figure the reference pins, byte for
//  byte — that file is the cross-port parity claim, and it is the same 31,647
//  bytes in TypeScript and in Swift.
//
//  The corpus lives in `mdTests/PlotVectors/`, **not** in `mdTests/TestData/`:
//  that directory is a four-repo mirror of *Markdown* fixtures whose roster is
//  pinned twice in every repo (`TestDataTests.swift:17-21` and `:31-36`), and a
//  JSON corpus is not a Markdown fixture.
//

import XCTest
@testable import md

final class PlotTests: XCTestCase {

    // MARK: - The corpus

    /// `nan`, `inf` and `-inf` are JSON strings — JSON has no literal for them.
    enum Real: Decodable {
        case number(Double)
        case symbol(String)

        init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            if let value = try? container.decode(Double.self) {
                self = .number(value)
                return
            }
            self = .symbol(try container.decode(String.self))
        }

        var value: Double {
            switch self {
            case let .number(value): return value
            case let .symbol(text):
                if text == "nan" { return Double.nan }
                if text == "inf" { return Double.infinity }
                if text == "-inf" { return -Double.infinity }
                return Double(text) ?? Double.nan
            }
        }

        var label: String {
            switch self {
            case let .number(value): return "\(value)"
            case let .symbol(text): return text
            }
        }
    }

    struct RustPrimitives: Decodable {
        let fmt_1e: String
        let fmt_2f: String
        let as_i64: String
        let round: String
    }

    struct NiceStepRow: Decodable {
        let input: Real
        let inputBits: String
        let output: Real
        let outputBits: String
    }

    struct FormatLabelRow: Decodable {
        let input: Real
        let inputBits: String
        let output: String
        let rustPrimitives: RustPrimitives
    }

    struct EvalRow: Decodable {
        let expr: String
        let x: Real
        let xBits: String
        /// Null for the 41 rows the site could not evaluate at all — every one
        /// of them a corrected behaviour or a name this language does not have,
        /// and the loop below fails if any is neither.
        let result: Real?
        let resultBits: String?
    }

    struct ParseErrorRow: Decodable {
        let expr: String
        let stage: String
        let error: String?
    }

    struct SVGRow: Decodable {
        let name: String
        let expr: String
        let xMin: Double
        let xMax: Double
        let yMin: Double
        let yMax: Double
        let firstPoint: String?
        let lastPoint: String?
        let polylineCount: Int
        let lineCount: Int
        let textCount: Int
        let xStep: Double
        let yStep: Double
        let xTickLabels: [String]
        let yTickLabels: [String]
    }

    struct Vectors: Decodable {
        let niceStep: [NiceStepRow]
        let formatLabel: [FormatLabelRow]
        let eval: [EvalRow]
        let parseErrors: [ParseErrorRow]
        let svg: [SVGRow]
    }

    /// Read once, from a copy inside the test bundle, so the corpus travels with
    /// the repository and a run needs nothing outside it.
    ///
    /// `JSONDecoder`, never `JSONSerialization`: Foundation's older parser is not
    /// correctly rounded — it reads `0.019999999999999997` as
    /// `0.019999999999999993`, three ulp out — and a corpus whose whole point is
    /// the last bit cannot be read through it. The per-row `inputBits`
    /// assertions below are what proves the decoder used here is exact.
    static let vectors: Vectors = {
        guard let url = Bundle(for: PlotTests.self)
            .url(forResource: "plot-vectors", withExtension: "json", subdirectory: "PlotVectors"),
              let data = try? Data(contentsOf: url),
              let decoded = try? JSONDecoder().decode(Vectors.self, from: data) else {
            fatalError("missing or unreadable PlotVectors/plot-vectors.json")
        }
        return decoded
    }()

    /// The big-endian IEEE-754 bit pattern, the way the vectors record a double.
    private func bits(_ value: Double) -> String {
        String(format: "%016llx", value.bitPattern)
    }

    private func value(_ expr: String, _ x: Double) throws -> Double {
        Plot.evaluate(try Plot.parseExpression(expr, "x"), "x", x)
    }

    /// Assert that `body` throws a `PlotError` whose message contains `message`.
    private func assertPlotError<T>(_ body: @autoclosure () throws -> T, _ message: String,
                                    _ note: String = "",
                                    file: StaticString = #filePath, line: UInt = #line) {
        do {
            _ = try body()
            XCTFail("expected a PlotError containing '\(message)' \(note)", file: file, line: line)
        } catch let error as PlotError {
            guard !message.isEmpty else { return }
            XCTAssertTrue(error.message.contains(message),
                          "'\(error.message)' should contain '\(message)' \(note)",
                          file: file, line: line)
        } catch {
            XCTFail("expected a PlotError, got \(error) \(note)", file: file, line: line)
        }
    }

    // MARK: - §1 nice_step — ported verbatim, so every row must match

    func testNiceStepReproducesAllRecordedSpacings() {
        XCTAssertEqual(Self.vectors.niceStep.count, 81)
        for row in Self.vectors.niceStep {
            XCTAssertEqual(bits(row.input.value), row.inputBits,
                           "the corpus decodes exactly: \(row.input.label)")
            XCTAssertEqual(bits(Plot.niceStep(row.input.value)), row.outputBits,
                           "niceStep(\(row.input.label))")
        }
    }

    func testNiceStepTakesEachOfTheFourBranches() {
        // norm <= 1.5, <= 3, <= 7, else — the `10 * mag` branch is the one a
        // careless port drops, and it is what draws [-32, 32] with a step of 10.
        XCTAssertEqual(Plot.niceStep(8), 1)
        XCTAssertEqual(Plot.niceStep(20), 2)
        XCTAssertEqual(Plot.niceStep(50), 5)
        XCTAssertEqual(Plot.niceStep(64), 10)
    }

    // MARK: - §2 format_label — ported with two corrections

    /// The nine labels the site prints wrong, and what this renderer prints
    /// instead.
    ///
    /// All nine are the same defect: `format_label`'s integer branch prints
    /// `val as i64`, which **truncates**, so a tick that arrives one ULP below a
    /// whole number loses a whole unit. SPEC §1.4 replaces the truncation with a
    /// round, which is what `round()` in the same condition already implied.
    private static let correctedLabels: [(input: Double, site: String, ours: String)] = [
        (0.9999999999, "0", "1"),
        (-0.9999999999, "0", "-1"),
        (2.9999999996, "2", "3"),
        (-2.9999999996, "-2", "-3"),
        (999.9999999999, "999", "1000"),
        (-999.9999999999, "-999", "-1000"),
        (123.99999999995, "123", "124"),
        (-123.99999999995, "-123", "-124"),
        (999.9999999999999, "999", "1000"),
    ]

    private func correctedLabel(_ input: Real) -> (input: Double, site: String, ours: String)? {
        guard case let .number(value) = input else { return nil }
        for row in Self.correctedLabels where row.input == value { return row }
        return nil
    }

    func testFormatLabelReproducesEveryRecordedLabelButTheNineTheSiteTruncates() {
        XCTAssertEqual(Self.vectors.formatLabel.count, 100)
        var corrected = 0
        for row in Self.vectors.formatLabel {
            XCTAssertEqual(bits(row.input.value), row.inputBits,
                           "the corpus decodes exactly: \(row.input.label)")
            let got = Plot.formatLabel(row.input.value)
            if let fix = correctedLabel(row.input) {
                XCTAssertEqual(row.output, fix.site,
                               "the vector still records the site's \(row.input.label)")
                XCTAssertEqual(got, fix.ours, "formatLabel(\(row.input.label))")
                corrected += 1
            } else {
                XCTAssertEqual(got, row.output, "formatLabel(\(row.input.label))")
            }
        }
        // Every row of the correction table was reached — a table entry that no
        // vector exercises is a claim about nothing.
        XCTAssertEqual(corrected, Self.correctedLabels.count)
    }

    func testFormatLabelWritesRustsExponentialNotThePlatforms() {
        // THE cross-platform hazard, pinned on all 100 values: `1.0e3` and not
        // `1.0e+3` (JavaScript), `1.0e+03` (C — which is what `String(format:)`
        // calls — and Java) or `1.0E3`; and ties to even on the exact binary
        // value, not the half-up rounding `%.1e` performs.
        for row in Self.vectors.formatLabel {
            XCTAssertEqual(Plot.formatExponential(row.input.value, 1), row.rustPrimitives.fmt_1e,
                           "{:.1e} of \(row.input.label)")
        }
        // What the platform would have said. Darwin's `printf` is correctly
        // rounded and rounds ties to even, so it gets 1.25 right where Java and
        // JavaScript round it up — but it still writes the C spelling, with a
        // `+` and a zero-padded exponent, which is neither Rust's nor what the
        // other three ports must produce.
        XCTAssertEqual(String(format: "%.1e", 1250.0), "1.2e+03")
        XCTAssertEqual(Plot.formatExponential(1250, 1), "1.2e3")   // 1.25 → ties to even
        XCTAssertEqual(Plot.formatExponential(1350, 1), "1.4e3")   // 1.35 → ties to even, upward
        XCTAssertEqual(Plot.formatExponential(0.0125, 1), "1.3e-2") // not a tie: the double is above it
        XCTAssertEqual(Plot.formatExponential(5e-324, 1), "4.9e-324") // the smallest subnormal
    }

    func testFormatLabelWritesRustsFixedFormNotThePlatforms() {
        for row in Self.vectors.formatLabel {
            // Past 25 significant digits `{:.2}` prints the double's whole exact
            // expansion (1e300 is 301 digits of it). `format_label` sends
            // everything from 1000 up to the exponential branch, so the fixed
            // formatter is never asked for one, and it stops at the digits it can
            // decide a rounding on.
            if row.rustPrimitives.fmt_2f.count > 30 { continue }
            XCTAssertEqual(Plot.formatFixed(row.input.value, 2), row.rustPrimitives.fmt_2f,
                           "{:.2} of \(row.input.label)")
        }
        // What the platform would have said. On this platform the digits agree —
        // Darwin rounds the 0.125 tie to even, where `toFixed` and Java's
        // `String.format` both write 0.13 — but the formatter is still written
        // by hand: the four ports have to agree with each other rather than
        // each with its own libc, and `%.2f` of 1e300 is 301 digits of exact
        // expansion rather than a tick label.
        XCTAssertEqual(String(format: "%.2f", 0.125), "0.12")
        XCTAssertEqual(Plot.formatFixed(0.125, 2), "0.12")     // an exact tie, rounded to even
        XCTAssertEqual(Plot.formatFixed(8.125, 2), "8.12")
        XCTAssertEqual(Plot.formatFixed(2.675, 2), "2.67")     // the double is below the tie
        XCTAssertEqual(Plot.formatFixed(999.999, 2), "1000.00") // the carry runs off the fraction
        XCTAssertEqual(Plot.formatFixed(-0.0, 2), "-0.00")     // Rust keeps the sign
    }

    // MARK: - §3 The expression language

    /// The evaluations where this renderer deliberately answers differently.
    ///
    /// Four of the five families are SPEC §1.3's corrections; the fifth is the
    /// `math::` prefix, which is not a language feature at all but the site's own
    /// preprocessor showing through — it rewrites every roster name to `math::…`
    /// before handing the text to evalexpr, so `math::sin(x)` happens to work
    /// there. It is not in the roster, so it is a parse error here.
    private static let correctedEval: [(expr: String, x: Double?, value: Double, why: String)] = [
        // 1. floor / ceil / round draw. The site registers them bare and then
        //    asks evalexpr for `math::floor`, which is unbound, so all 1001
        //    samples fail and `broken_floor_no_curve.svg` has no polyline at all.
        ("floor(x)", 2.7, 2, "floor works"),
        ("floor(x)", -2.5, -3, "floor works"),
        ("ceil(x)", 2.1, 3, "ceil works"),
        ("ceil(x)", -2.5, -2, "ceil works"),
        ("round(x)", 2.5, 3, "round works, ties away from zero"),
        ("round(x)", -2.5, -3, "round works, ties away from zero"),
        ("round(x)", 0.5, 1, "round works, ties away from zero"),
        // 2. Comparisons and the Boolean operators are numbers, so they compose.
        ("x==1", 1, 1, "comparisons yield 1.0 / 0.0"),
        ("x!=1", 1, 0, "comparisons yield 1.0 / 0.0"),
        ("x<1", 0, 1, "comparisons yield 1.0 / 0.0"),
        ("x<=1", 1, 1, "comparisons yield 1.0 / 0.0"),
        ("x>1", 2, 1, "comparisons yield 1.0 / 0.0"),
        ("x>=1", 1, 1, "comparisons yield 1.0 / 0.0"),
        ("(x>0)*2", 1, 2, "a comparison multiplies"),
        ("!x", 1, 0, "negation is numeric"),
        ("1&&1", nil, 1, "a number is a truth value"),
        ("1<2<3", nil, 1, "comparisons chain left-associatively"),
        // 3. `^` is right-associative.
        ("2^3^2", nil, 512, "2^(3^2), not (2^3)^2"),
        // 4. Everything is a double.
        ("5/2", nil, 2.5, "no integer division"),
        ("-7/2", nil, -3.5, "no integer division"),
        ("7/2", nil, 3.5, "no integer division"),
        ("2+3*4-5/2", nil, 11.5, "no integer division"),
        ("1/0", nil, Double.infinity, "division by zero is ±∞, not an error"),
        ("0/0", nil, Double.nan, "0/0 is NaN, not an error"),
        ("1%0", nil, Double.nan, "x%0 is NaN, not an error"),
    ]

    /// Expressions this language does not have.
    ///
    /// Every one of them is a **parse error** here, which is the point: on the
    /// site most of these parse and then die silently at evaluation time, which
    /// is why a typo currently looks like an empty chart rather than a message.
    private static let notInTheLanguage: [String] = [
        // Not in the roster. evalexpr carries them; the four ports share a roster.
        "min(x,0)", "max(x,0)", "if(x>0,1,-1)", "log(8,2)", "typeof(x)",
        // The site's preprocessor showing through.
        "math::floor(x)", "math::sin(x)", "math::math::sin(x)", "math::log(8,2)",
        // Unknown names, and names that are nearly right.
        "mysin(x)", "x_sin(x)", "SIN(x)", "sinx", "foo(x)", "y", "X",
        "true&&false", "true||false", "!true",
        // Wrong arity — an error, not a silently empty chart.
        "sqrt(1,2)", "hypot(3)", "atan2(1)", "sin()",
        // Types and syntax the language has no use for.
        "\"abc\"", "(1,2)", "x=1", "0x10",
    ]

    // There is no libm-tolerance table, and the deleted one is worth a note so
    // it is not re-added by reflex. It named `atanh(x)`, `asin(x)` and
    // `acos(x)` at x = 0.5 as rows "where the platform's libm and Rust's libm
    // disagree in the last bit" and let them through on a 1e-15 relative
    // tolerance. The claim was false. Decoding the oracle's own bits and
    // comparing them with Apple's libm:
    //
    //     atanh(0.5)  oracle 3fe193ea7aad030b   Darwin 3fe193ea7aad030b
    //     asin(0.5)   oracle 3fe0c152382d7365   Darwin 3fe0c152382d7365
    //     acos(0.5)   oracle 3ff0c152382d7365   Darwin 3ff0c152382d7365
    //
    // All three are exact, so all 162 rows are asserted bit for bit below and a
    // one-ULP drift in any function is now a failure rather than a pass. If a
    // machine ever *does* disagree, name that machine and that row here with
    // its bits — do not restore a blanket tolerance.

    private func corrected(_ expr: String, _ x: Double) -> (value: Double, why: String)? {
        for row in Self.correctedEval {
            if row.expr != expr { continue }
            if let wanted = row.x, wanted != x { continue }
            return (row.value, row.why)
        }
        return nil
    }

    func testExpressionLanguageAccountsForEveryRecordedEvaluation() throws {
        XCTAssertEqual(Self.vectors.eval.count, 162)
        var seenCorrections = Set<String>()
        var seenAbsences = Set<String>()

        for row in Self.vectors.eval {
            let x = row.x.value
            let label = "\(row.expr) at x=\(row.x.label)"
            XCTAssertEqual(bits(x), row.xBits, "the corpus decodes exactly: \(label)")

            if let fix = corrected(row.expr, x) {
                seenCorrections.insert(row.expr)
                let got = try value(row.expr, x)
                if fix.value.isNaN {
                    XCTAssertTrue(got.isNaN, label)
                } else {
                    XCTAssertEqual(got, fix.value, "\(label) — \(fix.why)")
                }
                continue
            }

            if Self.notInTheLanguage.contains(row.expr) {
                seenAbsences.insert(row.expr)
                assertPlotError(try self.value(row.expr, x), "", label)
                continue
            }

            guard let recorded = row.result, let recordedBits = row.resultBits else {
                XCTFail("\(label): the site recorded no result, and no table claims the row")
                continue
            }
            let want = recorded.value
            let got = try value(row.expr, x)
            if want.isNaN {
                // NaN and not its payload: a runtime may return a quiet NaN spelt
                // 7ffc000000000000 where Rust's returns 7ff8000000000000, and no
                // program can tell the difference.
                XCTAssertTrue(got.isNaN, label)
                continue
            }
            XCTAssertEqual(bits(got), recordedBits, label)
        }

        // Both tables are fully exercised by the corpus.
        XCTAssertEqual(seenCorrections.count, Set(Self.correctedEval.map(\.expr)).count)
        XCTAssertEqual(seenAbsences.count, Self.notInTheLanguage.count)
    }

    func testExpressionLanguageRejectsEveryMalformedExpression() {
        XCTAssertEqual(Self.vectors.parseErrors.count, 38)
        for row in Self.vectors.parseErrors {
            // Two of the site's failures are not failures here, and both are in
            // the grammar on purpose: `floor(x)` is correction 1, and `x ++ 2` is
            // `x + (+2)` — unary plus is a prefix operator in SPEC §1.3's table.
            if row.expr == "floor(x)" || row.expr == "x ++ 2" { continue }
            assertPlotError(try self.value(row.expr, 1), "", row.expr)
        }
    }

    func testExpressionLanguageSaysWhatIsWrongInTheWordsTheSpecUses() {
        assertPlotError(try self.value("sinc(x)", 1), "unknown function 'sinc'")
        assertPlotError(try self.value("sin(x", 1), "expected ')'")
        assertPlotError(try self.value("sqrt(1,2)", 1), "sqrt takes 1 argument, not 2")
        assertPlotError(try self.value("y", 1), "unknown name 'y'")
    }

    func testExpressionLanguageBindsUnaryMinusLooserThanPowerAndPowerToTheRight() throws {
        XCTAssertEqual(try value("2^3^2", 0), 512)
        XCTAssertEqual(try value("2^(3^2)", 0), 512)
        XCTAssertEqual(try value("(2^3)^2", 0), 64)
        XCTAssertEqual(try value("-x^2", 3), -9)
        XCTAssertEqual(try value("(-x)^2", 3), 9)
        XCTAssertEqual(try value("-2^2", 0), -4)
        XCTAssertEqual(try value("2^-1", 0), 0.5)
        XCTAssertEqual(try value("-x", 3), -3)
        XCTAssertEqual(try value("--x", 3), 3)
    }

    func testExpressionLanguagePowerIsIEEECorrectForTheUnitBaseCases() throws {
        // IEEE 754-2019 §9.2 pins five results the naïve reading of "anything
        // to the power of NaN is NaN" gets wrong, and this platform already
        // gets all five right because Swift's `pow` is C's:
        //
        //     pow(1, y)  == 1 for every y, NaN included
        //     pow(±1, ±∞) == 1
        //
        // It is pinned here because it is the port that is *correct*: JavaScript
        // returns NaN for all five (ECMA-262 Number::exponentiate returns NaN
        // whenever the exponent is NaN, and NaN when |base| is 1 and the
        // exponent is infinite), and Java — so Kotlin — documents the same NaN
        // for an infinite exponent with |base| == 1. Those two ports are being
        // changed to match this file, so this test is the reference they are
        // matched against and must not be relaxed to "whatever the platform
        // does".
        let nan = try value("0/0", 0)
        XCTAssertTrue(nan.isNaN, "0/0 is the NaN these rows are built from")
        XCTAssertEqual(try value("pow(1, 0/0)", 0), 1.0)
        XCTAssertEqual(try value("pow(1, 1/0)", 0), 1.0)
        XCTAssertEqual(try value("pow(1, -1/0)", 0), 1.0)
        XCTAssertEqual(try value("pow(-1, 1/0)", 0), 1.0)
        XCTAssertEqual(try value("pow(-1, -1/0)", 0), 1.0)
        // `^` routes to the same `pow`, so it must agree row for row.
        XCTAssertEqual(try value("1^(0/0)", 0), 1.0)
        XCTAssertEqual(try value("1^(1/0)", 0), 1.0)
        XCTAssertEqual(try value("1^(-1/0)", 0), 1.0)
        XCTAssertEqual(try value("(-1)^(1/0)", 0), 1.0)
        XCTAssertEqual(try value("(-1)^(-1/0)", 0), 1.0)
        // And directly, so a change in the evaluator can never be mistaken for
        // a change in the platform's libm.
        XCTAssertEqual(pow(1.0, Double.nan), 1.0)
        XCTAssertEqual(pow(1.0, Double.infinity), 1.0)
        XCTAssertEqual(pow(1.0, -Double.infinity), 1.0)
        XCTAssertEqual(pow(-1.0, Double.infinity), 1.0)
        XCTAssertEqual(pow(-1.0, -Double.infinity), 1.0)
    }

    func testExpressionLanguageKnowsPiAndENothingElseWithoutParentheses() throws {
        XCTAssertEqual(try value("pi", 0), Double.pi)
        XCTAssertEqual(try value("e", 0), M_E)
        XCTAssertEqual(try value("e^2", 0), 7.3890560989306495)
        assertPlotError(try self.value("sin", 0), "sin is a function")
    }

    // MARK: - §4 The four corrected behaviours, as figures

    /// Everything a rendered figure can be asked about without an XML parser.
    private struct Facts {
        var lines: Int
        var texts: Int
        var polylines: Int
        var first: String?
        var last: String?
        var xLabels: [String]
        var yLabels: [String]
    }

    private func matches(_ pattern: String, _ group: Int, in text: String) -> [String] {
        guard let regex = try? NSRegularExpression(pattern: pattern) else { return [] }
        let string = text as NSString
        return regex.matches(in: text, range: NSRange(location: 0, length: string.length)).map {
            string.substring(with: $0.range(at: group))
        }
    }

    /// Every group of the first match, group 0 first, or nil when there is none.
    private func firstMatch(_ pattern: String, in text: String) -> [String]? {
        guard let regex = try? NSRegularExpression(pattern: pattern) else { return nil }
        let string = text as NSString
        guard let match = regex.firstMatch(
            in: text, range: NSRange(location: 0, length: string.length)) else { return nil }
        return (0..<match.numberOfRanges).map { string.substring(with: match.range(at: $0)) }
    }

    private func facts(_ svg: String) -> Facts {
        let runs = matches("<polyline points=\"([^\"]*)\"", 1, in: svg)
        let lastRun = runs.last.map { $0.components(separatedBy: " ") }
        return Facts(
            lines: matches("(<line )", 1, in: svg).count,
            texts: matches("(<text )", 1, in: svg).count,
            polylines: runs.count,
            first: runs.first.map { $0.components(separatedBy: " ")[0] },
            last: lastRun?.last,
            xLabels: matches("text-anchor=\"middle\">([^<]*)</text>", 1, in: svg),
            yLabels: matches("dominant-baseline=\"middle\">([^<]*)</text>", 1, in: svg))
    }

    private func figure(_ source: String) throws -> Facts {
        facts(try Plot.plotSVG(source))
    }

    func testCorrection1FloorCeilAndRoundDrawACurveWhereTheSiteDrawsNothing() throws {
        // `broken_floor_no_curve.svg` has 0 polylines. Here the staircase is one
        // run: floor(x) stays inside [-2, 2] for x in [-2, 3), and every step
        // lands inside the window, so nothing breaks it.
        let floor = try figure("x: -10..10\ny: -2..2\nfloor(x)")
        XCTAssertEqual(floor.polylines, 1)
        XCTAssertEqual(floor.first, "248.00,360.00")  // x = -2, y = -2: the bottom left
        XCTAssertEqual(floor.last, "377.48,40.00")    // x = 2.98, y = 2: the top of the last step
        XCTAssertGreaterThan(try figure("x: -10..10\ny: -2..2\nceil(x)").polylines, 0)
        XCTAssertGreaterThan(try figure("x: -10..10\ny: -2..2\nround(x)").polylines, 0)
    }

    func testCorrection2AComparisonIsANumberSoTheHalfDomainIdiomDraws() throws {
        // `boolean_no_curve.svg` has 0 polylines for `x>0`.
        let step = try figure("x: -10..10\ny: -2..2\nx>0")
        XCTAssertEqual(step.polylines, 1)
        XCTAssertEqual(step.first, "40.00,200.00")   // 0 at the far left
        XCTAssertEqual(step.last, "560.00,120.00")   // 1 at the far right

        // The spec's own idiom. It draws exactly the half-domain it names: NaN
        // times zero is still NaN, so the left half stays empty and the curve
        // begins at the origin.
        let half = try figure("x: -4..4\ny: -1..3\n(x>0)*sqrt(x)")
        XCTAssertEqual(half.polylines, 1)
        XCTAssertEqual(half.first, "300.00,280.00")  // x = 0, y = 0
        XCTAssertEqual(half.last, "560.00,120.00")   // x = 4, y = 2

        // And where the guard has a finite value on both sides it is a
        // full-width curve with a kink — a rectifier, drawn from edge to edge.
        let relu = try figure("x: -4..4\ny: -1..3\n(x>0)*x")
        XCTAssertEqual(relu.polylines, 1)
        XCTAssertEqual(relu.first, "40.00,280.00")
        // …until it climbs out of the window at y = 3, which is where the run ends.
        XCTAssertEqual(relu.last, "495.00,40.00")
    }

    func testCorrection3PowerIsRightAssociativeInAFigureToo() throws {
        // A constant series is a flat line, so its height *is* the value: with
        // y: 0..1024 the line at 512 lands exactly halfway.
        let chart = try figure("x: -1..1\ny: 0..1024\n2^3^2")
        XCTAssertEqual(chart.first, "40.00,200.00")
        XCTAssertEqual(chart.last, "560.00,200.00")
    }

    func testCorrection4FiveOverTwoIsTwoAndAHalfWhereTheSiteDrawsItAtTwo() throws {
        // `int_division_trunc.svg` puts the line at y = 232, which is sy(2).
        let chart = try figure("x: -1..1\ny: 0..5\n5/2")
        XCTAssertEqual(chart.first, "40.00,200.00")  // sy(2.5)
        XCTAssertEqual(chart.last, "560.00,200.00")
    }

    func testAxisCorrectionLabelsATickAtMinusFourMinusFour() throws {
        // `tick_label_truncation.svg`, both axes [-5, -3]: the site's sixth label
        // reads "-3", out of order, in the middle of the axis.
        let chart = try figure("x: -5..-3\ny: -5..-3\nx")
        XCTAssertEqual(chart.xLabels[5], "-4")
        XCTAssertEqual(chart.yLabels[5], "-4")
        XCTAssertEqual(chart.xLabels,
                       ["-5", "-4.80", "-4.60", "-4.40", "-4.20", "-4",
                        "-3.80", "-3.60", "-3.40", "-3.20", "-3"])
    }

    func testAxisCorrectionLabelsTheTickAtTheOriginZero() throws {
        // `tick_drift_zero_label.svg`: `gx += step` over [-1, 1] at 0.2 never
        // lands on zero. `first + i * step` does.
        let chart = try figure("x: -1..1\ny: -1..1\nx")
        XCTAssertEqual(chart.xLabels[5], "0")
        XCTAssertEqual(chart.yLabels[5], "0")
        // And `tick_drift_extra_tick.svg`, where the drift is 1.4e-16 instead.
        XCTAssertEqual(try figure("x: -0.9..0.3\ny: -0.9..0.3\nx").xLabels[9], "0")
    }

    func testAxisCorrectionKeepsTheTickThatLandsExactlyOnTheMaximum() throws {
        // The other half of computing by index: `0.0001 + 8 * 0.0001` is
        // 9.000000000000001e-4, a hair over the range's own maximum, and dropping
        // the last tick of an axis because of one ULP is a visible defect. The
        // site drops it (`tiny_range.svg` has eight ticks per axis).
        let chart = try figure("x: 0.0001..0.0009\ny: 0.0001..0.0009\nx")
        XCTAssertEqual(chart.xLabels.count, 9)
        XCTAssertEqual(chart.xLabels[8], "9.0e-4")
    }

    // MARK: - §5 The 22 recorded figures

    /// The figures whose recorded shape is one of the six corrected behaviours.
    ///
    /// Each entry lists only what differs from the vector; everything unlisted is
    /// still asserted against the site's own numbers.
    private struct FigureFix {
        var polylines: Int? = nil
        var first: String?? = nil
        var last: String?? = nil
        var lines: Int? = nil
        var texts: Int? = nil
        var xLabels: [String]? = nil
        var yLabels: [String]? = nil
        var why: String
    }

    private static let drift =
        ["-1", "-0.80", "-0.60", "-0.40", "-0.20", "0", "0.20", "0.40", "0.60", "0.80", "1"]
    private static let truncated =
        ["-5", "-4.80", "-4.60", "-4.40", "-4.20", "-4", "-3.80", "-3.60", "-3.40", "-3.20", "-3"]
    private static let tinyRange =
        ["1.0e-4", "2.0e-4", "3.0e-4", "4.0e-4", "5.0e-4", "6.0e-4", "7.0e-4", "8.0e-4", "9.0e-4"]
    private static let driftThirteen =
        ["-0.90", "-0.80", "-0.70", "-0.60", "-0.50", "-0.40", "-0.30", "-0.20", "-0.10", "0",
         "0.10", "0.20", "0.30"]

    private static let correctedFigures: [String: FigureFix] = [
        // floor(x) draws (correction 1).
        "broken_floor_no_curve": FigureFix(polylines: 1, first: "248.00,360.00",
                                           last: "377.48,40.00", why: "floor is bound"),
        // x>0 draws (correction 2).
        "boolean_no_curve": FigureFix(polylines: 1, first: "40.00,200.00", last: "560.00,120.00",
                                      why: "a comparison is a number"),
        // 5/2 is 2.5, and the origin's label is "0" and not "-5.6e-17".
        "int_division_trunc": FigureFix(first: "40.00,200.00", last: "560.00,200.00",
                                        xLabels: PlotTests.drift,
                                        why: "no integer division; no tick drift"),
        "constant_three": FigureFix(xLabels: PlotTests.drift, why: "no tick drift"),
        "tick_drift_zero_label": FigureFix(xLabels: PlotTests.drift, yLabels: PlotTests.drift, why: "no tick drift"),
        "tick_drift_extra_tick": FigureFix(xLabels: PlotTests.driftThirteen, yLabels: PlotTests.driftThirteen,
                                           why: "no tick drift"),
        // The truncated label, and the tick at the maximum the site's
        // accumulation overshot: eleven ticks per axis rather than ten.
        "tick_label_truncation": FigureFix(lines: 22, texts: 22, xLabels: PlotTests.truncated,
                                           yLabels: PlotTests.truncated,
                                           why: "labels are rounded, and the last tick is kept"),
        "no_zero_on_either_axis": FigureFix(
            lines: 20, texts: 20,
            xLabels: ["1", "1.20", "1.40", "1.60", "1.80", "2", "2.20", "2.40", "2.60", "2.80", "3"],
            why: "labels are rounded, and the last tick is kept"),
        "tiny_range": FigureFix(lines: 18, texts: 18, xLabels: PlotTests.tinyRange, yLabels: PlotTests.tinyRange,
                                why: "the tick on the maximum is kept"),
    ]

    /// A range end, spelled the way the fence reads it back as the same double.
    private func fenceNumber(_ v: Double) -> String {
        if v == v.rounded() && abs(v) < 1e15 { return String(Int(v)) }
        return "\(v)"
    }

    func testThirteenOfTheRecordedFiguresAreDrawnExactlyAsTheSiteDoes() {
        XCTAssertEqual(Self.vectors.svg.count, 22)
        var same = 0
        for row in Self.vectors.svg where Self.correctedFigures[row.name] == nil { same += 1 }
        XCTAssertEqual(same, 13)
    }

    func testTheTwentyTwoRecordedFigures() throws {
        for row in Self.vectors.svg {
            let source = "x: \(fenceNumber(row.xMin))..\(fenceNumber(row.xMax))\n"
                + "y: \(fenceNumber(row.yMin))..\(fenceNumber(row.yMax))\n\(row.expr)"
            let got = facts(try Plot.plotSVG(source))
            let fix = Self.correctedFigures[row.name]
            let name = "\(row.name): \(row.expr)"

            // The spacing is `nice_step`, ported verbatim: never corrected.
            XCTAssertEqual(bits(Plot.niceStep(row.xMax - row.xMin)), bits(row.xStep), name)
            XCTAssertEqual(bits(Plot.niceStep(row.yMax - row.yMin)), bits(row.yStep), name)

            XCTAssertEqual(got.lines, fix?.lines ?? row.lineCount, "\(name) — grid + axis lines")
            XCTAssertEqual(got.texts, fix?.texts ?? row.textCount, "\(name) — tick labels")
            XCTAssertEqual(got.polylines, fix?.polylines ?? row.polylineCount,
                           "\(name) — unbroken runs")
            XCTAssertEqual(got.first, fix?.first ?? row.firstPoint, "\(name) — first plotted point")
            XCTAssertEqual(got.last, fix?.last ?? row.lastPoint, "\(name) — last plotted point")
            XCTAssertEqual(got.xLabels, fix?.xLabels ?? row.xTickLabels, "\(name) — x tick labels")
            XCTAssertEqual(got.yLabels, fix?.yLabels ?? row.yTickLabels, "\(name) — y tick labels")
        }
    }

    func testBreaksACurveWhereItLeavesTheWindowAndNowhereElse() throws {
        // tan(x) over [-10, 10] is seven branches; 1/x over [-5, 5] is two; a
        // single plottable sample is still a polyline of one point.
        XCTAssertEqual(try figure("x: -10..10\ny: -2..2\ntan(x)").polylines, 7)
        XCTAssertEqual(try figure("x: -5..5\ny: -5..5\n1/x").polylines, 2)
        XCTAssertEqual(try figure("x: -10..10\ny: -0.005..0.005\nx").first, "300.00,200.00")
    }

    func testSamplesWithTheFormulaTheSiteUsesNotTheCheaperOne() throws {
        // `xMin + (i / samples) * span`, never `xMin + i * dx`: the two differ in
        // the last bits for 221 of the 1001 default samples, and the difference
        // reaches the output.
        let chart = try figure("x: -6.3..0.7999999999999998\ny: -3.3..3.1\nx")
        XCTAssertEqual(chart.first, "259.96,359.83")
        XCTAssertEqual(chart.last, "560.00,155.00")
    }

    // MARK: - §6 The fence

    func testFenceReadsDirectivesInAnyOrderAndIgnoresBlanksAndComments() throws {
        let spec = try Plot.parsePlot(
            ["# a comment", "", "sin(x)", "title: A title", "x: -1..1", "y: -2..2", ""]
                .joined(separator: "\n"))
        XCTAssertEqual(spec.title, "A title")
        XCTAssertEqual(spec.xMin, -1)
        XCTAssertEqual(spec.xMax, 1)
        XCTAssertEqual(spec.yMin, -2)
        XCTAssertEqual(spec.series.count, 1)
    }

    func testFenceTreatsAnUnknownKeyLineAsALabelledSeriesNotAnError() throws {
        // `f: x` still plots. This is why the directive scan checks the key
        // against the known list before it claims the line, and why the series
        // parser then reads the key as a label.
        let spec = try Plot.parsePlot("f: x")
        XCTAssertEqual(spec.series.count, 1)
        XCTAssertEqual(spec.series[0].label, "f")
        XCTAssertEqual(spec.series[0].source, "x")
        XCTAssertTrue(try Plot.plotSVG("f: sin(x)").contains("<polyline"))
    }

    func testFenceDefaultsToTheSitesGeometry() throws {
        let spec = try Plot.parsePlot("sin(x)")
        XCTAssertEqual([spec.xMin, spec.xMax], [-10, 10])
        XCTAssertNil(spec.yMin)
        XCTAssertEqual([spec.width, spec.height, spec.samples], [600, 400, 1000])
        XCTAssertEqual(spec.legend, .auto)
        XCTAssertTrue(spec.grid)
        XCTAssertTrue(spec.axes)
    }

    func testFenceClampsWidthHeightAndSamples() throws {
        let small = try Plot.parsePlot("width: 10\nheight: 10\nsamples: 1\nx")
        XCTAssertEqual(small.width, 160)
        XCTAssertEqual(small.height, 120)
        XCTAssertEqual(small.samples, 50)
        let large = try Plot.parsePlot("width: 9000\nheight: 9000\nsamples: 90000\nx")
        XCTAssertEqual(large.width, 2000)
        XCTAssertEqual(large.height, 2000)
        XCTAssertEqual(large.samples, 5000)
    }

    func testFenceTakesAConstantExpressionAtEitherEndOfARange() throws {
        let spec = try Plot.parsePlot("x: -pi..2*pi\nsin(x)")
        XCTAssertEqual(spec.xMin, -Double.pi)
        XCTAssertEqual(spec.xMax, 2 * Double.pi)
    }

    func testFenceRejectsARangeThatDoesNotIncrease() {
        assertPlotError(try Plot.parsePlot("x: 1..1\nx"), "x range must be increasing")
        assertPlotError(try Plot.parsePlot("y: 5..-5\nx"), "y range must be increasing")
        assertPlotError(try Plot.parsePlot("x: nonsense\nx"), "")
    }

    func testFenceSplitsALabelOffTheFirstTopLevelBareEquals() throws {
        XCTAssertEqual(try Plot.parsePlot("envelope = exp(-abs(x)/5)").series[0].label, "envelope")
        XCTAssertEqual(try Plot.parsePlot("envelope = exp(-abs(x)/5)").series[0].source,
                       "exp(-abs(x)/5)")
        // The FIRST one, so what follows still has to be an expression: there is
        // no assignment in the language for a second `=` to be part of.
        assertPlotError(try Plot.parsePlot("a = b = x"), "")
        // …and never off a comparison operator.
        for source in ["x == 1", "x <= 1", "x >= 1", "x != 1"] {
            XCTAssertNil(try Plot.parsePlot(source).series[0].label, source)
        }
    }

    func testFenceReadsAPointsSeriesAndAParametricSeries() throws {
        let points = try Plot.parsePlot("measured = points: 0,0 1,2 2,1").series[0]
        XCTAssertEqual(points.kind, .points)
        XCTAssertEqual(points.label, "measured")
        XCTAssertEqual(points.points,
                       [Plot.Point(x: 0, y: 0), Plot.Point(x: 1, y: 2), Plot.Point(x: 2, y: 1)])

        let parametric = try Plot.parsePlot("circle = (cos(t), sin(t)) for t in 0..2*pi").series[0]
        XCTAssertEqual(parametric.kind, .parametric)
        XCTAssertEqual(parametric.parameter, "t")
        XCTAssertEqual(parametric.tMin, 0)
        XCTAssertEqual(parametric.tMax, 2 * Double.pi)
        // The parametric variable is the only free name inside it: `x` is not.
        assertPlotError(try Plot.parsePlot("(x, sin(t)) for t in 0..1"), "unknown name 'x'")
    }

    func testFenceDoesNotMistakeAParenthesisedExpressionForAParametricOne() throws {
        XCTAssertEqual(try Plot.parsePlot("(x+1)*2").series[0].kind, .function)
        // A pair with no `for` is not a parametric series, so it is read as an
        // expression — and a tuple is not one of those.
        assertPlotError(try Plot.parsePlot("(x, x)"), "")
    }

    func testFenceFitsYAutoToTheFiniteSamplesWithFivePercentOfPadding() throws {
        // sin over a whole period reaches ±1 (to the last sample), so the window
        // is 1.05 either way.
        XCTAssertTrue(try Plot.plotSVG("x: -10..10\nsin(x)").contains(">1</text>"))
        // A series with nothing finite in it falls back to -1..1.
        XCTAssertTrue(try Plot.plotSVG("x: -10..10\nsqrt(-1)+x*0").contains(">1</text>"))
        // A flat series has no span to take 5 % of: it is padded by 5 % of itself.
        XCTAssertEqual(try Plot.parsePlot("x: -1..1\n3").series.count, 1)
        XCTAssertTrue(try Plot.plotSVG("x: -1..1\n3").contains("<polyline"))
    }

    func testFenceShowsTheLegendForTwoSeriesOrOneThatIsLabelled() throws {
        XCTAssertFalse(try Plot.plotSVG("x: -1..1\nsin(x)")
            .contains("font-size=\"11\" font-family=\"sans-serif\""))
        XCTAssertTrue(try Plot.plotSVG("x: -1..1\nsin(x)\ncos(x)")
            .contains("font-size=\"11\" font-family=\"sans-serif\""))
        XCTAssertTrue(try Plot.plotSVG("x: -1..1\nwave = sin(x)").contains(">wave</text>"))
        XCTAssertFalse(try Plot.plotSVG("x: -1..1\nlegend: off\nsin(x)\ncos(x)")
            .contains("font-size=\"11\" font-family=\"sans-serif\""))
        // An unlabelled series' legend text is its own source.
        XCTAssertTrue(try Plot.plotSVG("x: -1..1\nlegend: on\nsin(x)").contains(">sin(x)</text>"))
    }

    func testFenceTurnsTheGridAndTheAxesOff() throws {
        let bare = try Plot.plotSVG("x: -1..1\ngrid: off\naxes: off\nx")
        XCTAssertFalse(bare.contains("<line"))
        XCTAssertFalse(bare.contains("<text x="))
        XCTAssertFalse(bare.contains("<rect"))
        XCTAssertTrue(bare.contains("<polyline"))
        assertPlotError(try Plot.parsePlot("grid: sometimes\nx"), "grid must be 'on' or 'off'")
    }

    func testFenceGivesEachSeriesTheNextColourPurpleFirst() throws {
        let svg = try Plot.plotSVG("x: -1..1\nx\nx+0.1\nx+0.2")
        XCTAssertTrue(svg.contains("stroke=\"#673AB7\""))
        XCTAssertTrue(svg.contains("stroke=\"#E5390F\""))
        XCTAssertTrue(svg.contains("stroke=\"#0F9D58\""))
    }

    // MARK: - §7 The container, and what must never be in it

    func testMarkupIsADivPlotAroundOneSvgWithAViewBox() {
        let block = Plot.renderPlot("x: -10..10\nsin(x)")
        XCTAssertTrue(block.hasPrefix("<div class=\"plot\"><svg "))
        XCTAssertTrue(block.hasSuffix("</svg></div>"))
        // Without a viewBox, `max-width: 100%; height: auto` shrinks the box and
        // clips the drawing instead of scaling it.
        XCTAssertTrue(block.contains("viewBox=\"0 0 600 400\""))
        XCTAssertTrue(block.contains("width=\"600\" height=\"400\" role=\"img\""))
    }

    func testMarkupCarriesNoIdAtAll() throws {
        // SPEC §1.5: a duplicated id is how one figure ends up wearing another's
        // clip path once a document holds two plots. An `<svg role="img">` is
        // named by its own `<title>`, with no `aria-labelledby` to point at, so
        // there is nothing to number.
        let two = Plot.renderPlot("sin(x)") + Plot.renderPlot("cos(x)")
        XCTAssertFalse(two.contains(" id="))
        XCTAssertFalse(two.contains("aria-labelledby"))
        XCTAssertTrue(try Plot.plotSVG("x: -10..10\ntitle: T\nsin(x)").contains("<title>T</title>"))
        XCTAssertTrue(try Plot.plotSVG("sin(x)").contains("<title>Plot of sin(x)</title>"))
    }

    func testMarkupPaintsWithCurrentColorAndBakesOnlyTheSeriesColours() throws {
        // `renderBlock` is theme-blind in all four repos, so one SVG has to be
        // right in a light preview, a dark preview, print, an exported page and a
        // saved file. A baked grey is a light-mode assumption.
        let svg = try Plot.plotSVG("x: -10..10\ntitle: T\nsin(x)")
        XCTAssertTrue(svg.contains("stroke=\"currentColor\""))
        XCTAssertTrue(svg.contains("fill=\"currentColor\""))
        for grey in ["#e0e0e0", "#999", "#666", "#ccc"] {
            XCTAssertFalse(svg.contains(grey), grey)
        }
        XCTAssertFalse(svg.contains("background:white"))
        XCTAssertTrue(svg.contains("stroke=\"#673AB7\""))
    }

    func testMarkupEmbedsNoStyleScriptForeignObjectOrFont() throws {
        // An SVG `<style>` inside an HTML document is document-scoped and leaks.
        let svg = try Plot.plotSVG("x: -10..10\ntitle: T\nsin(x)")
        for forbidden in ["<style", "<script", "<foreignObject", "@font-face", "<image"] {
            XCTAssertFalse(svg.contains(forbidden), forbidden)
        }
    }

    func testMarkupXMLEscapesEveryAuthorStringWithTheFourEntitiesAndNoOther() throws {
        // The EPUB body is XHTML, which is XML: one raw `&` makes the whole
        // content document unparseable and the book unopenable. And a named
        // entity like `&nbsp;` is undefined in XML, so escaping may only ever
        // produce entities XML predefines.
        //
        // Four, not five: `&apos;` is never emitted, because a bare `'` is
        // well-formed both in text and inside the double-quoted attributes this
        // renderer writes — and because the reference escapes exactly these four
        // (`md.vscode/src/render/inline.ts`), which is what the byte-parity
        // golden below depends on. An apostrophe in a title therefore travels
        // through as itself, and that is asserted here rather than left implied.
        let hostile = try Plot.plotSVG(
            ["title: A & B <c> \"d\" 'e'", "xlabel: <x>", "ylabel: &y;", "p & q = x"]
                .joined(separator: "\n"))
        XCTAssertTrue(hostile.contains("<title>A &amp; B &lt;c&gt; &quot;d&quot; 'e'</title>"))
        XCTAssertTrue(hostile.contains(">&lt;x&gt;</text>"))
        XCTAssertTrue(hostile.contains(">&amp;y;</text>"))
        XCTAssertTrue(hostile.contains(">p &amp; q</text>"))
        XCTAssertFalse(hostile.contains("&nbsp;"))
        XCTAssertFalse(hostile.contains("&apos;"))
        for entity in matches("(&[a-z]+;)", 1, in: hostile) {
            XCTAssertTrue(["&amp;", "&lt;", "&gt;", "&quot;"].contains(entity), entity)
        }
    }

    func testMarkupEmitsTheContainerEvenForAnEmptyBlockAndABrokenOne() {
        // If it is ever omitted the SVG-export ordinals desynchronise and every
        // later diagram exports the wrong figure.
        XCTAssertEqual(Plot.renderPlot(""), "<div class=\"plot\"></div>")
        XCTAssertEqual(Plot.renderPlot("# only a comment"), "<div class=\"plot\"></div>")
        let broken = Plot.renderPlot("sinc(x)")
        XCTAssertTrue(broken.hasPrefix("<div class=\"plot\"><pre>"))
        XCTAssertTrue(broken.contains("plot: unknown function 'sinc'"))
        XCTAssertTrue(broken.contains("sinc(x)"))  // the source always stays visible
        XCTAssertTrue(Plot.renderPlot("x: 1..1\nx").contains("plot: x range must be increasing"))
    }

    func testMarkupEscapesTheSourceItFallsBackTo() {
        XCTAssertTrue(Plot.renderPlot("<b>&</b>").contains("&lt;b&gt;&amp;&lt;/b&gt;"))
    }

    func testMarkupNeverReturnsAnythingButAContainerWhateverItIsHanded() {
        // The renderer runs inside the Markdown renderer, which has no other
        // failure mode: whatever a fence contains, the answer is a `div.plot`
        // with either a drawing or the source in it, and every coordinate in that
        // drawing is a real number. The resource guards are what keep the deep
        // and the long ones out of the recursion — on this platform a stack
        // overflow is a crash, not something a `catch` could turn back into the
        // author's own text.
        let hostile = [
            "", "   ", "#", "x: 0..0\nx", "y: 1..0\nx", "width: -5\nheight: abc\nx",
            "points:", "points: 1", "label =", "= x", "(cos(t), sin(t)) for t in 0..0",
            "(cos(t), sin(t)) for u in 0..1", "x: 1e308..-1e308\nx", "x: -1e308..1e308\nx",
            "x: 0.0000001..0.0000002\nx", "axes: off\ngrid: off\nx", "ln(x)", "x^x",
            "sqrt(-x)", "0/0", "x*0/0", String(repeating: "(", count: 200) + "x",
            "title: " + String(repeating: "A", count: 500) + "\nx",
            "y: -1..1\n" + String(repeating: "sin(x)\n", count: 12),
        ]
        for source in hostile {
            let html = Plot.renderPlot(source)
            XCTAssertTrue(html.hasPrefix("<div class=\"plot\">"), source)
            XCTAssertTrue(html.hasSuffix("</div>"), source)
            for number in matches(" (?:x|y|x1|y1|x2|y2|width|height|cx|cy)=\"([^\"]*)\"", 1,
                                  in: html) {
                XCTAssertTrue(Double(number).map { $0.isFinite } ?? false,
                              "\(source) → \(number)")
            }
            for run in matches("points=\"([^\"]*)\"", 1, in: html) {
                for pair in run.components(separatedBy: " ") {
                    let parts = pair.components(separatedBy: ",")
                    XCTAssertEqual(parts.count, 2, pair)
                    for part in parts {
                        XCTAssertTrue(Double(part).map { $0.isFinite } ?? false, pair)
                    }
                }
            }
        }
    }

    func testMarkupSurvivesAFigureSqueezedToTheSmallestCanvas() throws {
        // Title, both axis labels and a legend on a 160 × 120 canvas would compute
        // a negative plot area without `fitMargins`.
        let tiny = try Plot.plotSVG(
            ["width: 160", "height: 120", "title: T", "xlabel: x", "ylabel: y", "legend: on",
             "a = x"].joined(separator: "\n"))
        XCTAssertTrue(tiny.contains("viewBox=\"0 0 160 120\""))
        XCTAssertFalse(tiny.contains("NaN"))
        // The plot area is still a real rectangle, inside the canvas.
        let rect = try XCTUnwrap(firstMatch(
            "<rect x=\"([\\d.]+)\" y=\"([\\d.]+)\" width=\"([\\d.]+)\" height=\"([\\d.]+)\"",
            in: tiny))
        let x = try XCTUnwrap(Double(rect[1])), y = try XCTUnwrap(Double(rect[2]))
        let w = try XCTUnwrap(Double(rect[3])), h = try XCTUnwrap(Double(rect[4]))
        XCTAssertGreaterThanOrEqual(w, 40)
        XCTAssertGreaterThanOrEqual(h, 40)
        XCTAssertLessThanOrEqual(x + w, 160)
        XCTAssertLessThanOrEqual(y + h, 120)
    }

    // MARK: - §8 The renderer, and every export path

    private static let fence = ["```plot", "x: -10..10", "sin(x)", "```"].joined(separator: "\n")

    func testIntegrationDispatchesTheFenceToAPlotContainerAndLoadsNoEngine() {
        let html = MarkdownHTML.document(Self.fence, title: "t", dark: false)
        XCTAssertTrue(html.contains("<div class=\"plot\"><svg"))
        // The class is exactly `plot`, which keeps all five engine probes false:
        // a plot-only document loads no engine at all, and there is no `needs`
        // flag to add.
        for engine in ["mermaid.min.js", "viz-global.js", "katex.min.js", "mhchem.min.js",
                       "highlight.min.js"] {
            XCTAssertFalse(html.contains(engine), engine)
        }
        // …nor is it code: `plot` joins the fences highlight.js never sees.
        XCTAssertFalse(html.contains("language-plot"))
    }

    func testIntegrationIsStyledByTheScreenAndTheExportStylesheet() {
        // The rules are *joined*, never added: `.plot` rides the container rule
        // the other rich blocks share, and `.plot svg` the cap rule that gives an
        // SVG with a viewBox its responsive size. Both variants carry them —
        // `export: true` is the sheet print, PDF and the standalone page use.
        for export in [false, true] {
            let html = MarkdownHTML.document(Self.fence, title: "t", dark: false, export: export)
            XCTAssertTrue(html.contains(".mermaid, .plantuml, .graphviz, .plot, .md-mathd {"),
                          "export=\(export)")
            XCTAssertTrue(html.contains(
                ".mermaid svg, .plantuml svg, .graphviz svg, .plot svg { max-width: 100%; height: auto; }"),
                          "export=\(export)")
        }
    }

    func testIntegrationOffersTheFigureToTheSVGExportAndFindsItInTheDOM() {
        let document = [Self.fence, "", "```dot", "digraph {}", "```"].joined(separator: "\n")
        let found = DiagramSVG.diagrams(inSource: document)
        XCTAssertEqual(found.map(\.kind), [.plot, .graphviz])
        XCTAssertEqual(found[0].typeName, "Plot")
        XCTAssertEqual(found[0].menuTitle, "Plot: x: -10..10")
        // The walk and the DOM query must agree about what a diagram is, or every
        // later figure exports as the wrong one. (That the query really finds the
        // container is proven against a live WKWebView in `RichRenderTests`.)
        XCTAssertTrue(DiagramSVG.domSelector.contains("div.plot"))
        // A quoted plot keeps its place, because the renderer recurses into quotes.
        XCTAssertEqual(
            DiagramSVG.diagrams(inSource: ["> ```plot", "> sin(x)", "> ```"]
                .joined(separator: "\n")).map(\.kind),
            [.plot])
    }

    func testIntegrationSavesAsAStandaloneSVGWithoutAFixUp() throws {
        // The root already carries `xmlns`, `width` and `height`, so the only
        // thing the writer adds is the XML prolog.
        let file = DiagramSVG.standaloneDocument(fromSVG: try Plot.plotSVG("sin(x)"))
        XCTAssertTrue(file.hasPrefix("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns="))
        XCTAssertTrue(file.contains("width=\"600\" height=\"400\""))
    }

    func testIntegrationKeepsTheSourceInTheLaTeXExportUnderAComment() {
        let tex = LaTeXExport.document(Self.fence)
        XCTAssertTrue(tex.contains("% plot diagram source"))
        XCTAssertTrue(tex.contains("\\begin{verbatim}"))
        XCTAssertTrue(tex.contains("sin(x)"))
    }

    func testIntegrationPassesTheEpubXhtmlFixerUntouchedAndAsksForPropertiesSvg() {
        // The fixer has never seen an SVG before: `xhtmlBody` self-closes void
        // elements with an *unanchored* alternation, so `<line>` and `<polyline>`
        // are exactly the shapes to check before trusting it.
        let block = Plot.renderPlot("x: -10..10\nsin(x)")
        XCTAssertTrue(block.contains("<line "))
        XCTAssertTrue(block.contains("<polyline "))
        XCTAssertEqual(EPUBExport.xhtmlBody(block), block)

        // EPUB 3 requires the reserved property on any content document holding
        // an `<svg>`; without it EPUBCheck reports OPF-014 and the book is
        // invalid.
        XCTAssertTrue(EPUBExport.opf(title: "t", identifier: "i", modified: "m",
                                     units: ["content.xhtml"], images: [], svgUnits: [0])
            .contains("<item id=\"u0\" href=\"content.xhtml\" "
                      + "media-type=\"application/xhtml+xml\" properties=\"svg\"/>"))
        // …and a document without one is still emitted bare.
        XCTAssertTrue(EPUBExport.opf(title: "t", identifier: "i", modified: "m",
                                     units: ["content.xhtml"], images: [])
            .contains("<item id=\"u0\" href=\"content.xhtml\" "
                      + "media-type=\"application/xhtml+xml\"/>"))
    }

    func testIntegrationFlagsTheDocumentEPUBsContentFileWhenItHoldsAPlot() {
        // The whole path, not just the builder: `documentEntries` decides the
        // flag from the finished XHTML body, which is where a plot's `<svg>`
        // survives and a Mermaid diagram's does not (that one is a PNG by now).
        func packageDocument(body: String) -> String {
            let entries = EPUBExport.documentEntries(
                title: "t", body: body, images: [], outline: [],
                modified: "2026-08-29T00:00:00Z")
            guard let opf = entries.first(where: { $0.name == "OEBPS/content.opf" }),
                  let text = String(data: opf.data, encoding: .utf8) else { return "" }
            return text
        }
        XCTAssertTrue(packageDocument(body: Plot.renderPlot("x: -10..10\nsin(x)"))
            .contains("properties=\"svg\""))
        XCTAssertFalse(packageDocument(body: "<p>Just prose.</p>").contains("properties=\"svg\""))
    }

    func testIntegrationLeavesAPlotOutOfTheRichContainersTheEPUBPhotographs() {
        // SPEC §1.6: those three lists exist to photograph DOM the markup does
        // not contain. A plot is already an `<svg>` in the string the renderer
        // returned — 16,888 bytes of vector against a 169,108-byte PNG of the
        // same figure — so a plot-only document never opens a web view at all.
        let block = Plot.renderPlot("x: -10..10\nsin(x)")
        XCTAssertFalse(EPUBExport.containsRichContent(block))
        XCTAssertEqual(EPUBExport.replacingRichElements(in: block, with: ["<img src=\"x.png\">"]),
                       block)
    }

    // MARK: - §9 The figure itself, byte for byte

    func testGoldenDrawsTheSpecsOwnExampleAsRecorded() throws {
        // The whole SVG of one document, pinned. Not a specification and not
        // documentation: a tripwire, so that a change to a coordinate, an opacity
        // or an attribute order shows up as a diff to read rather than as nothing
        // at all.
        //
        // It is also **the cross-port parity claim**: this is byte for byte the
        // file `md.vscode` pins at `test/fixtures/golden/plot-damped-oscillation.svg`,
        // produced by the same fence in TypeScript.
        let source = [
            "x: -10..10",
            "y: -2..2",
            "title: Damped oscillation",
            "xlabel: x",
            "ylabel: amplitude",
            "envelope = exp(-abs(x)/5)",
            "sin(x) * exp(-abs(x)/5)",
        ].joined(separator: "\n")
        let url = try XCTUnwrap(
            Bundle(for: PlotTests.self).url(forResource: "plot-damped-oscillation",
                                            withExtension: "svg", subdirectory: "PlotVectors"),
            "missing PlotVectors/plot-damped-oscillation.svg")
        let golden = try Data(contentsOf: url)
        let drawn = Data((Plot.renderPlot(source) + "\n").utf8)
        XCTAssertEqual(drawn.count, golden.count, "byte count")
        XCTAssertEqual(drawn, golden, "the figure is not byte-identical to the reference golden")
    }

    // MARK: - §10 Resource limits and degenerate magnitudes

    // Each of these was found by an adversarial pass against the first cut of the
    // reference, and each is a way it could have taught the same defect to this
    // port. A stack overflow is an exception there and a **crash** here, so the
    // guards matter more in this file than in that one.

    func testDrawsASeriesWhoseValuesOverflowThePaddedRange() {
        // `high - low` overflows for a series straddling ~1e308, which made every
        // sy() NaN and emitted points="40.00,NaN …" — a curve that vanished with
        // nothing to say why.
        let out = Plot.renderPlot("x: -10..10\nx*1e307")
        XCTAssertFalse(out.contains("NaN"))
        XCTAssertTrue(out.contains("<polyline"))
    }

    func testLeavesAHugeButNarrowRangeExactlyAsAsked() {
        // The guard must fire on an overflowing *width*, not on a large bound:
        // [1.69e308, 1.71e308] is only 2e306 wide and is perfectly drawable.
        let out = Plot.renderPlot("x: -1..1\ny: 1.69e308..1.71e308\n1.7e308")
        XCTAssertFalse(out.contains("NaN"))
        XCTAssertTrue(out.contains("<polyline"))
    }

    func testReportsDeepNestingAsAPlotLineNotAStackOverflow() {
        let source = "x: -1..1\n" + String(repeating: "(", count: 5000) + "x"
            + String(repeating: ")", count: 5000)
        XCTAssertTrue(Plot.renderPlot(source).contains("plot: expression nested too deeply"))
    }

    func testReportsALongFlatChainTooWhichTheDepthGuardCannotSee() {
        // `x+x+x+…` parses at constant depth through the left-associative loop and
        // then overflows the stack in the evaluator, so depth alone is not enough.
        let source = "x: -1..1\nx" + String(repeating: "+x", count: 20000)
        XCTAssertTrue(Plot.renderPlot(source).contains("plot: expression too large"))
    }

    func testCapsTheSeriesCountTheOneInputWithNoClamp() {
        var lines = ["x: -1..1"]
        for index in 1...1000 { lines.append("x*\(index)") }
        XCTAssertTrue(Plot.renderPlot(lines.joined(separator: "\n"))
            .contains("plot: too many series"))
    }

    func testDrawsTheAxesADirectivesOnlyBlockDescribes() {
        // Not an empty block: the author wrote three lines. Returning an empty
        // container would swallow them, and the family rule is never a hole.
        let out = Plot.renderPlot("x: -10..10\ntitle: My chart\nylabel: y")
        XCTAssertTrue(out.contains("<svg"))
        XCTAssertTrue(out.contains("My chart"))
    }

    func testStillDrawsNothingForAGenuinelyEmptyBlock() {
        XCTAssertEqual(Plot.renderPlot(""), "<div class=\"plot\"></div>")
    }

    // MARK: - §11 The memo
    //
    // Why the renderer has one at all is in `PlotMemo`'s own comment: the live
    // preview rebuilds the whole HTML document on every text change, and a plot
    // is the first rich block whose cost is paid *there*, synchronously, rather
    // than asynchronously by an engine in the page. What these tests pin is that
    // it is a memo and not a leak — a repeat render is served from it, and it
    // stops at 32 entries.
    //
    // The memo is one static, so each test clears it first. The test target
    // runs serially (no `parallelizable` in md.xcscheme), so a clear here cannot
    // race another class's render.

    func testMemoServesARepeatRenderWithoutRedrawingIt() {
        Plot.clearMemo()
        let source = "x: -10..10\ntitle: T\nsin(x)"

        let first = Plot.renderPlot(source)
        XCTAssertEqual(Plot.memoStatistics, PlotMemo.Statistics(entries: 1, hits: 0, misses: 1))

        let second = Plot.renderPlot(source)
        XCTAssertEqual(second, first, "a hit must be the same bytes as the miss it replays")
        XCTAssertEqual(Plot.memoStatistics, PlotMemo.Statistics(entries: 1, hits: 1, misses: 1),
                       "the second render must be served from the memo, not redrawn")

        // A different fence is a different key — the memo is keyed on the exact
        // source, so one keystroke's difference is a miss, as it must be.
        _ = Plot.renderPlot(source + " * 2")
        XCTAssertEqual(Plot.memoStatistics, PlotMemo.Statistics(entries: 2, hits: 1, misses: 2))
    }

    func testMemoCachesFailuresToo() {
        // The state a fence spends most of its life in while it is being typed.
        // Re-deriving "unknown function 'sinc'" on every keystroke buys nothing,
        // and the container it produces is what the reader sees, so it is the
        // container that is stored.
        Plot.clearMemo()
        let broken = "x: -10..10\nsinc(x)"
        let first = Plot.renderPlot(broken)
        XCTAssertTrue(first.contains("plot: unknown function 'sinc'"))
        let second = Plot.renderPlot(broken)
        XCTAssertEqual(second, first)
        XCTAssertEqual(Plot.memoStatistics, PlotMemo.Statistics(entries: 1, hits: 1, misses: 1))
    }

    func testMemoEvictsTheLeastRecentlyUsedEntryAtThirtyTwo() {
        Plot.clearMemo()
        func fence(_ index: Int) -> String { "x: -10..10\nsin(x) + \(index)" }

        for index in 0..<32 { _ = Plot.renderPlot(fence(index)) }
        XCTAssertEqual(Plot.memoStatistics.entries, 32, "the ceiling is 32 entries")
        XCTAssertEqual(Plot.memoStatistics.misses, 32)
        XCTAssertEqual(Plot.memoStatistics.hits, 0)

        // Touch 0 so it is the *most* recently used; 1 is then the oldest.
        _ = Plot.renderPlot(fence(0))
        XCTAssertEqual(Plot.memoStatistics.hits, 1)

        // The 33rd entry evicts the least recently used, which is now 1 — not 0.
        _ = Plot.renderPlot(fence(32))
        XCTAssertEqual(Plot.memoStatistics.entries, 32, "it never grows past the limit")

        let beforeProbe = Plot.memoStatistics
        _ = Plot.renderPlot(fence(0))
        XCTAssertEqual(Plot.memoStatistics.hits, beforeProbe.hits + 1,
                       "the entry used most recently must have survived")
        _ = Plot.renderPlot(fence(1))
        XCTAssertEqual(Plot.memoStatistics.misses, beforeProbe.misses + 1,
                       "the least recently used entry must have been evicted")
        XCTAssertEqual(Plot.memoStatistics.entries, 32)
    }

    func testMemoIsSafeToShareBetweenThreads() {
        // Not a race detector — a smoke test for the lock. The export paths
        // (PDF, HTML, EPUB, LaTeX, diagram-as-SVG) build their markup off the
        // main thread while the preview may be rendering on it, so two threads
        // really are inside `renderPlot` at once. Without the lock this is an
        // unsynchronised `Dictionary`, which crashes rather than reading stale.
        Plot.clearMemo()
        let sources = (0..<8).map { "x: -10..10\nsin(x) * \($0 + 1)" }
        let expected = sources.map { Plot.renderPlot($0) }
        Plot.clearMemo()

        DispatchQueue.concurrentPerform(iterations: 200) { iteration in
            let index = iteration % sources.count
            XCTAssertEqual(Plot.renderPlot(sources[index]), expected[index])
        }
        XCTAssertEqual(Plot.memoStatistics.entries, sources.count)
        XCTAssertEqual(Plot.memoStatistics.hits + Plot.memoStatistics.misses, 200)
    }

    func testMemoDoesNotChangeWhatTheRendererReturns() throws {
        // The whole safety argument is that a memo of a pure function returns
        // what recomputing would. Cleared or warm, the golden fence is the same
        // bytes — which is also the one thing that could silently break parity.
        let source = [
            "x: -10..10", "y: -2..2", "title: Damped oscillation",
            "xlabel: x", "ylabel: amplitude",
            "envelope = exp(-abs(x)/5)", "sin(x) * exp(-abs(x)/5)",
        ].joined(separator: "\n")
        Plot.clearMemo()
        let cold = Plot.renderPlot(source)
        let warm = Plot.renderPlot(source)
        Plot.clearMemo()
        let coldAgain = Plot.renderPlot(source)
        XCTAssertEqual(warm, cold)
        XCTAssertEqual(coldAgain, cold)

        let url = try XCTUnwrap(
            Bundle(for: PlotTests.self).url(forResource: "plot-damped-oscillation",
                                            withExtension: "svg", subdirectory: "PlotVectors"))
        XCTAssertEqual(Data((warm + "\n").utf8), try Data(contentsOf: url))
    }
}
