//
//  SmartTypingTests.swift
//  mdTests
//
//  `SmartTyping.enter` and `SmartTyping.capitalize` against the family's
//  shared oracle.
//
//  WHERE THE EXPECTATIONS COME FROM
//  --------------------------------
//  `TypingVectors/typing-vectors.json` was generated by the TypeScript
//  reference implementation of the SmartTyping specification (SPEC.md v1,
//  FINAL) over 1350 inputs — 512 for `enter`, 838 for `capitalize` — and is
//  copied verbatim into every port: this file, `md`, `md.Android` and
//  `md.win`. Every offset in it is a UTF-16 unit, every `null` is the JSON
//  literal, and the file is ASCII-only with `\uXXXX` escapes so that no
//  editor can normalise an invisible unit on the way in.
//
//  It is normative: no row is skipped and there is no correction table. A
//  port that disagrees with a vector is wrong, and a disputed vector is
//  changed in the JSON first, in one commit across all repos. The two
//  vector loops below assert every row, ordinally (unit for unit — a Swift
//  `String` compares by canonical equivalence, which would let an NFD
//  answer pass against an NFC expectation), and name the vector on failure.
//
//  The hand-written cases after them are for the reader: one per headline
//  behaviour, in prose. The last test is an informational timing of the
//  §0.14 cost contract on a 1 MB document; it logs and never asserts a
//  wall-clock bound, because CI machines are slower than this one.
//
//  The corpus lives in `mdTests/TypingVectors/`, **not** in `mdTests/TestData/`:
//  that directory is a four-repo mirror of *Markdown* fixtures whose roster is
//  pinned twice in every repo, and a JSON corpus is not a Markdown fixture.
//
//  This file is byte-identical in `md` and `md.macOS`.
//

import XCTest
@testable import md

final class SmartTypingTests: XCTestCase {

    // MARK: - The corpus

    struct EnterExpected: Decodable {
        let location: Int
        let length: Int
        let replacement: String
        let caret: Int
    }

    struct EnterVector: Decodable {
        let id: String
        let note: String?
        let text: String
        let start: Int
        let end: Int
        /// The JSON literal `null` decodes to nil.
        let expected: EnterExpected?
    }

    struct CapitalizeVector: Decodable {
        let id: String
        let note: String?
        let text: String
        let start: Int
        let end: Int
        let typed: String
        /// The JSON literal `null` decodes to nil.
        let expected: String?
    }

    struct Counts: Decodable {
        let enter: Int
        let capitalize: Int
    }

    struct Meta: Decodable {
        let counts: Counts
    }

    struct Vectors: Decodable {
        let _meta: Meta
        let enter: [EnterVector]
        let capitalize: [CapitalizeVector]
    }

    /// Read once, from a copy inside the test bundle, so the corpus travels with
    /// the repository and a run needs nothing outside it.
    static let vectors: Vectors = {
        guard let url = Bundle(for: SmartTypingTests.self)
            .url(forResource: "typing-vectors", withExtension: "json", subdirectory: "TypingVectors"),
              let data = try? Data(contentsOf: url),
              let decoded = try? JSONDecoder().decode(Vectors.self, from: data) else {
            fatalError("missing or unreadable TypingVectors/typing-vectors.json")
        }
        return decoded
    }()

    /// A string as the vectors spell it: ASCII as is, everything else as
    /// `\uXXXX`, so a failure message shows the unit that differs.
    private func escaped(_ s: String?) -> String {
        guard let s = s else { return "null" }
        var out = "\""
        for u in s.utf16 {
            switch u {
            case 0x22: out += "\\\""
            case 0x5c: out += "\\\\"
            case 0x0a: out += "\\n"
            case 0x20...0x7e: out += String(UnicodeScalar(UInt8(u)))
            default: out += String(format: "\\u%04x", u)
            }
        }
        return out + "\""
    }

    private func describe(_ e: SmartTyping.EnterEdit?) -> String {
        guard let e = e else { return "null" }
        return "{location: \(e.location), length: \(e.length), replacement: \(escaped(e.replacement)), caret: \(e.caret)}"
    }

    private func describe(_ e: EnterExpected?) -> String {
        guard let e = e else { return "null" }
        return "{location: \(e.location), length: \(e.length), replacement: \(escaped(e.replacement)), caret: \(e.caret)}"
    }

    /// Ordinal string equality: unit for unit, never canonical equivalence.
    private func same(_ a: String?, _ b: String?) -> Bool {
        switch (a, b) {
        case (nil, nil): return true
        case let (a?, b?): return Array(a.utf16) == Array(b.utf16)
        default: return false
        }
    }

    // MARK: - §1 enter — every vector

    func testEnterVectorsAllMatch() {
        let vectors = Self.vectors
        XCTAssertEqual(vectors.enter.count, vectors._meta.counts.enter, "the corpus is whole")
        XCTAssertEqual(vectors.enter.count, 512)
        var failures = 0
        for v in vectors.enter {
            let actual = SmartTyping.enter(v.text, selectionStart: v.start, selectionEnd: v.end)
            let matches: Bool
            switch (actual, v.expected) {
            case (nil, nil):
                matches = true
            case let (a?, e?):
                matches = a.location == e.location && a.length == e.length && a.caret == e.caret
                    && same(a.replacement, e.replacement)
            default:
                matches = false
            }
            if !matches {
                failures += 1
                XCTFail("enter vector \(v.id)\(v.note.map { " (\($0))" } ?? ""): "
                        + "text \(escaped(v.text)) [\(v.start), \(v.end)] — "
                        + "expected \(describe(v.expected)), actual \(describe(actual))")
            }
        }
        XCTAssertEqual(failures, 0, "\(failures) of \(vectors.enter.count) enter vectors failed")
    }

    // MARK: - §2 capitalize — every vector

    func testCapitalizeVectorsAllMatch() {
        let vectors = Self.vectors
        XCTAssertEqual(vectors.capitalize.count, vectors._meta.counts.capitalize, "the corpus is whole")
        XCTAssertEqual(vectors.capitalize.count, 838)
        var failures = 0
        for v in vectors.capitalize {
            XCTAssertEqual(v.typed.unicodeScalars.count, 1, "\(v.id): typed is one scalar")
            let actual = SmartTyping.capitalize(v.text, selectionStart: v.start, selectionEnd: v.end, typed: v.typed)
            if !same(actual, v.expected) {
                failures += 1
                XCTFail("capitalize vector \(v.id)\(v.note.map { " (\($0))" } ?? ""): "
                        + "text \(escaped(v.text)) [\(v.start), \(v.end)] + \(escaped(v.typed)) — "
                        + "expected \(escaped(v.expected)), actual \(escaped(actual))")
            }
        }
        XCTAssertEqual(failures, 0, "\(failures) of \(vectors.capitalize.count) capitalize vectors failed")
    }

    func testCorpusHoldsThirteenHundredAndFiftyUniqueVectors() {
        let vectors = Self.vectors
        let ids = vectors.enter.map(\.id) + vectors.capitalize.map(\.id)
        XCTAssertEqual(ids.count, 1350)
        XCTAssertEqual(Set(ids).count, ids.count, "every id is unique across both arrays")
    }

    // MARK: - Hand-written, for the reader

    func testEnterContinuesABulletItem() {
        let text = "- item"
        let edit = SmartTyping.enter(text, selectionStart: 6, selectionEnd: 6)
        XCTAssertEqual(edit, SmartTyping.EnterEdit(location: 6, length: 0, replacement: "\n- ", caret: 9))
    }

    func testEnterContinuesAnOrderedItemWithTheNextNumber() {
        let text = "3) c"
        let edit = SmartTyping.enter(text, selectionStart: 4, selectionEnd: 4)
        XCTAssertEqual(edit, SmartTyping.EnterEdit(location: 4, length: 0, replacement: "\n4) ", caret: 8))
    }

    func testEnterOnAnEmptyItemEndsTheList() {
        // `- a⏎- |`: the empty item is replaced by an empty line
        let text = "- a\n- "
        let edit = SmartTyping.enter(text, selectionStart: 6, selectionEnd: 6)
        XCTAssertEqual(edit, SmartTyping.EnterEdit(location: 4, length: 2, replacement: "", caret: 4))
    }

    func testEnterOnAnEmptyNestedItemOutdents() {
        let text = "- a\n  - "
        let edit = SmartTyping.enter(text, selectionStart: 8, selectionEnd: 8)
        XCTAssertEqual(edit, SmartTyping.EnterEdit(location: 4, length: 4, replacement: "- ", caret: 6))
    }

    func testEnterInATableRowInsertsARow() {
        // Enter at the end of the last body row adds `|  |  |` below it, with
        // the caret after the new row's first `| `
        let text = "| a | b |\n|---|---|\n| 1 | 2 |"
        let edit = SmartTyping.enter(text, selectionStart: text.utf16.count, selectionEnd: text.utf16.count)
        XCTAssertEqual(edit, SmartTyping.EnterEdit(location: 29, length: 0, replacement: "\n|  |  |", caret: 32))
    }

    func testEnterOnAHeaderRowInsertsAfterTheDelimiter() {
        let text = "| a | b |\n|---|---|"
        let edit = SmartTyping.enter(text, selectionStart: 9, selectionEnd: 9)
        XCTAssertEqual(edit, SmartTyping.EnterEdit(location: 19, length: 0, replacement: "\n|  |  |", caret: 22))
    }

    func testEnterOnAParagraphOrAHeadingIsAPlainNewline() {
        XCTAssertNil(SmartTyping.enter("# Title", selectionStart: 7, selectionEnd: 7))
        XCTAssertNil(SmartTyping.enter("plain text", selectionStart: 10, selectionEnd: 10))
        XCTAssertNil(SmartTyping.enter("", selectionStart: 0, selectionEnd: 0))
    }

    func testCapitalizeAtALineStart() {
        XCTAssertEqual(SmartTyping.capitalize("", selectionStart: 0, selectionEnd: 0, typed: "h"), "H")
        XCTAssertEqual(SmartTyping.capitalize("Notes\n", selectionStart: 6, selectionEnd: 6, typed: "j"), "J")
        XCTAssertEqual(SmartTyping.capitalize("- ", selectionStart: 2, selectionEnd: 2, typed: "i"), "I")
        XCTAssertEqual(SmartTyping.capitalize("> ", selectionStart: 2, selectionEnd: 2, typed: "b"), "B")
    }

    func testCapitalizeAfterASentenceEnd() {
        XCTAssertEqual(SmartTyping.capitalize("Hello. ", selectionStart: 7, selectionEnd: 7, typed: "w"), "W")
        XCTAssertEqual(SmartTyping.capitalize("Really?! ", selectionStart: 9, selectionEnd: 9, typed: "y"), "Y")
        // an abbreviation, an ellipsis and a mid-word letter are not sentence ends
        XCTAssertNil(SmartTyping.capitalize("e.g. ", selectionStart: 5, selectionEnd: 5, typed: "n"))
        XCTAssertNil(SmartTyping.capitalize("wait... ", selectionStart: 8, selectionEnd: 8, typed: "w"))
        XCTAssertNil(SmartTyping.capitalize("don'", selectionStart: 4, selectionEnd: 4, typed: "t"))
    }

    func testCapitalizeNeverInsideAFence() {
        let text = "```\n"
        XCTAssertNil(SmartTyping.capitalize(text, selectionStart: 4, selectionEnd: 4, typed: "t"))
        let closed = "```\ncode\n```\n"
        XCTAssertEqual(SmartTyping.capitalize(closed, selectionStart: 13, selectionEnd: 13, typed: "t"), "T",
                       "the line after the closer is prose again")
    }

    func testCapitalizeLeavesNonLowercaseInputAlone() {
        // an uppercase letter, a digit and a scalar without a one-scalar
        // uppercase mapping (§0.7) are returned as nil: insert as typed
        XCTAssertNil(SmartTyping.capitalize("", selectionStart: 0, selectionEnd: 0, typed: "H"))
        XCTAssertNil(SmartTyping.capitalize("", selectionStart: 0, selectionEnd: 0, typed: "7"))
        XCTAssertNil(SmartTyping.capitalize("", selectionStart: 0, selectionEnd: 0, typed: "ß"))
        XCTAssertNil(SmartTyping.capitalize("", selectionStart: 0, selectionEnd: 0, typed: "\u{00B5}"))
        XCTAssertNil(SmartTyping.capitalize("", selectionStart: 0, selectionEnd: 0, typed: "\u{10D0}"))
    }

    // MARK: - §0.14 cost contract (informational)

    /// A 1 MB document with the caret at its end: both functions must feel
    /// instantaneous, since they run on every keystroke on the UI thread. The
    /// timings are logged, not asserted — CI machines are slower than this
    /// one, and a wall-clock bound in a unit test is a flake waiting to fire.
    func testOneMegabyteDocumentTiming() {
        let paragraph = """
        # Section

        Some prose with a sentence. Another one follows, e.g. this one, and a third? Yes.
        A second line of the same paragraph, with `code`, $math$ and a [link](https://x.y/z).

        - item one
        - item two with more words in it
          - nested item

        > a quote line
        > another

        | a | b |
        |---|---|
        | 1 | 2 |

        ```
        fenced code that must not count
        ```


        """
        var text = ""
        while text.utf8.count < 1_048_576 { text += paragraph }
        text += "- last item"
        let end = text.utf16.count
        XCTAssertGreaterThanOrEqual(text.utf8.count, 1_048_576)

        let t0 = DispatchTime.now().uptimeNanoseconds
        let edit = SmartTyping.enter(text, selectionStart: end, selectionEnd: end)
        let t1 = DispatchTime.now().uptimeNanoseconds
        let cap = SmartTyping.capitalize(text + "\n", selectionStart: end + 1, selectionEnd: end + 1, typed: "t")
        let t2 = DispatchTime.now().uptimeNanoseconds

        XCTAssertEqual(edit?.replacement, "\n- ", "the last item continues")
        XCTAssertEqual(cap, "T", "the line after it starts with a capital")
        let enterMs = Double(t1 - t0) / 1_000_000
        let capitalizeMs = Double(t2 - t1) / 1_000_000
        print("SmartTyping timing on a \(text.utf8.count)-byte document (\(end) units): "
              + "enter \(String(format: "%.1f", enterMs)) ms, capitalize \(String(format: "%.1f", capitalizeMs)) ms "
              + "(informational; the §0.14 target is under 100 ms each on a developer machine)")
    }
}
